<?php
return json_decode('[{
		"genreId": 36,
		"name": "Overall"
	}, {
		"genreId": 6014,
		"name": "Games"
	}, {
		"genreId": 6000,
		"name": "Business"
	}, {
		"genreId": 6001,
		"name": "Weather"
	}, {
		"genreId": 6002,
		"name": "Utilities"
	}, {
		"genreId": 6003,
		"name": "Travel"
	}, {
		"genreId": 6004,
		"name": "Sports"
	}, {
		"genreId": 6005,
		"name": "Social Networking"
	}, {
		"genreId": 6006,
		"name": "Reference"
	}, {
		"genreId": 6007,
		"name": "Productivity"
	}, {
		"genreId": 6008,
		"name": "Photo & Video"
	}, {
		"genreId": 6009,
		"name": "News"
	}, {
		"genreId": 6010,
		"name": "Navigation"
	}, {
		"genreId": 6011,
		"name": "Music"
	}, {
		"genreId": 6012,
		"name": "Lifestyle"
	}, {
		"genreId": 6013,
		"name": "Health & Fitness"
	}, {
		"genreId": 6015,
		"name": "Finance"
	}, {
		"genreId": 6016,
		"name": "Entertainment"
	}, {
		"genreId": 6017,
		"name": "Education"
	}, {
		"genreId": 6018,
		"name": "Book"
	}, {
		"genreId": 6020,
		"name": "Medical"
	}, {
		"genreId": 6021,
		"name": "Magazines & Newspapers"
	}, {
		"genreId": 6023,
		"name": "Food & Drink"
	}, {
		"genreId": 6024,
		"name": "Shopping"
	}, {
		"genreId": 6026,
		"name": "Developer Tools"
	}, {
		"genreId": 6027,
		"name": "Graphics and Design"
	}, {
		"genreId": 7001,
		"name": "Action"
	}, {
		"genreId": 7002,
		"name": "Adventure"
	}, {
		"genreId": 7003,
		"name": "Arcade"
	}, {
		"genreId": 7004,
		"name": "Board"
	}, {
		"genreId": 7005,
		"name": "Card"
	}, {
		"genreId": 7006,
		"name": "Casino"
	}, {
		"genreId": 7009,
		"name": "Family"
	}, {
		"genreId": 7011,
		"name": "Music"
	}, {
		"genreId": 7012,
		"name": "Puzzle"
	}, {
		"genreId": 7013,
		"name": "Racing"
	}, {
		"genreId": 7014,
		"name": "Role Playing"
	}, {
		"genreId": 7015,
		"name": "Simulation"
	}, {
		"genreId": 7016,
		"name": "Sports"
	}, {
		"genreId": 7017,
		"name": "Strategy"
	}, {
		"genreId": 7018,
		"name": "Trivia"
	}, {
		"genreId": 7019,
		"name": "Word"
	}]', true);